package constant;

public enum OperationFeedback {
	
	VALID,
	START_DATE_TIME_LESS_THAN_CURRENT_DATE_TIME,
	END_DATE_TIME_LESS_THAN_CURRENT_DATE_TIME,
	START_DATE_TIME_MORE_THAN_END_DATE_TIME,
	INVALID_DATE_TIME,
	RECURRING_TIMES_EXCEEDED,
	INVALID_DATE,
	INVALID_TIME,
	INVALID_TASK_DETAILS,
	INVALID_LABEL,
	NOT_FOUND,
	UNDO_UNSUCCESSFUL,
	REDO_UNSUCCESSFUL,
	UNDO_SUCCESSFUL,
	REDO_SUCCESSFUL,
	UNDO_EMPTY,
	REDO_EMPTY,
	LOGGED_OUT_SUCCESSFULLY,
	LOGOUT_FAILED,
	INVALID_INCORRECTLOGIN, //incorrect username or password
	INVALID_NOINTERNET,
	ADD_FAILED,
	DELETE_FAILED,
	EDIT_FAILED,
	STAR_FAILED,
	COMPLETE_FAILED,
	OVERDUE_FAILED, 
	BASESEARCH_FAILED,
	ARCHIVE_FAILED,
	TASK_COULD_NOT_BE_EXPORTED_FROM_ARCHIVES,
	TASK_COULD_NOT_BE_EXPORTED_TO_ARCHIVES,
	NO_TASK_IN_ARCHIVE,
	NO_TASK_TO_ARCHIVE,
	NO_TASK_DELETED,
	NO_TASK_OVERDUE,
	NO_TASK_COMPLETED,
	NO_TASK_STARRED,
	GOOGLE_CALENDAR_FAILED;
	
	
	//not connect to internet
	
	
	private String msg;
	
	public void setMsg(String msg) {
		this.msg = msg;
	}
	
	public String getMsg() {
		return this.msg;
	}
}
