/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.mainWindow.extended;


import gui.Resource;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;
import javax.swing.JFrame;


/**
 *
 * @author Ramon
 */
public class TopPopUp extends JFrame {

    /**
     * Creates new form TopPopUp
     */
    public static void createTopPopUp() {
    	jFrame = new JFrame();
    	jFrame.setUndecorated(true);
    	initComponents();
    	jFrame.setFocusableWindowState(false);
    	//showBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private static void initComponents() {
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        jFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.setBounds(330, 0, 21, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 320, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        bgLabel.setBounds(0, 0, 400, 20);
        bgLabel.setIcon(Resource.topPopUpBG);
        bgLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLayeredPane1.add(bgLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jFrame.getContentPane());
        jFrame.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        
        jButton1.setText("");
        jButton1.setIcon( Resource.exitImg);
        jButton1.addActionListener( new 
        	ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					if(SHOW) {
						SHOW = !SHOW;
						jFrame.setVisible(false);
					}
				}
        	
        });
        

        jFrame.setIconImage((Resource.bigLogo).getImage());
        jFrame.pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    public static javax.swing.JFrame jFrame;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JButton jButton1;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLayeredPane jLayeredPane1;
    private static javax.swing.JLabel bgLabel;
    private static boolean SHOW = true;
    private static Timer timer;
    private final static int VISIBLE_TIME = 5;
    //private Timer timer;
    // End of variables declaration
    
    
    public static void setPosition(int x, int y) {
    	jFrame.setLocation(x, y);
    }
    
    public static void setText(String str) {
    	jLabel1.setText(str);
    }
    
    public static void showBox() {

    	SHOW = true;
    	jFrame.setVisible(SHOW);
    	jFrame.toFront();
    	
    	if(timer != null){
    		timer.stop();
    	}
    	timer = new Timer(VISIBLE_TIME * 1000, new ActionListener(){
	
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				hideBox();
			}
	    	
	    });
	    timer.setRepeats(false);
	    timer.start(); 

    }
    
    public static void hideBox() {
    	SHOW = false;
    	jFrame.setVisible(SHOW);
    }
    
    public static boolean isShow() {
    	return SHOW;
    }
    
}