/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

import logic.JIDLogic;

import data.*;
/**
 *
 * @author Ramon
 */
public class ExpandJPanel extends javax.swing.JPanel {

	static AutoUpdateJTable autoJTable;
	
    /**
     * Creates new form ExpandJPanel
     */
    public ExpandJPanel() {
        initComponents();
        autoJTable = new AutoUpdateJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(378, 300));
        setRequestFocusEnabled(false);

        jTable1.setModel(new MyTableModel());
        jTable1.setTableHeader(null);
        //jTable1.setCellEditor(jTable1.getCellEditor());
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(true);
        jTable1.setFocusable(true);
        jTable1.setMaximumSize(new java.awt.Dimension(370, 30));
        jTable1.setMinimumSize(new java.awt.Dimension(370, 370));
        jTable1.setRowSelectionAllowed(true);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowSorter(null);
        
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    
    // End of variables declaration
    public void updateJTable(Task[] tasks) {
    	autoJTable.updateJTable(tasks);
    }
    
    public static void updateJTable() {
    	autoJTable.updateJTable();
    }
    
    public static Task[] getTasks() {
    	return autoJTable.getTasks();
    }
    
    class MyTableModel extends DefaultTableModel{
    	MyTableModel() {
    		super(
    			new Object [][] {null},
    			new String [] {"Title 1"});
    	}
    	
    	@Override
    	public boolean isCellEditable(int row, int column) {
			return false;
    	}
    }

    protected void addBindings() {
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = this.getActionMap();
        
        //Ctrl-b to go backward one character
        KeyStroke key = KeyStroke.getKeyStroke(KeyEvent.VK_D, Event.CTRL_MASK);
        inputMap.put(key, "delete");
        actionMap.put("delete", new DeleteAction());
    }
    
    class DeleteAction extends AbstractAction {
        @Override
        public void actionPerformed(ActionEvent e) {
        	System.out.println("*****EXECMD: DELETE*******");
        	
        	JIDLogic.setCommand("find");
        	Task[] taskList = JIDLogic.executeCommand("find");
        	
        	JIDLogic.setCommand("DELETE");
        	Task[] task = JIDLogic.executeCommand("DELETE" + jTable1.getSelectedRow());
        	
        	if(task == null)
        		MainJFrame.showPopup("DELETE unsuccessfully!");
        	else {
        		MainJFrame.showPopup("DELETE: "+task[0].getName());
            	updateJTable();
        	}        	
        }
    }
}
