/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.table.DefaultTableModel;
import data.*;
/**
 *
 * @author Ramon
 */
public class ExpandJPanel extends javax.swing.JPanel {

	static AutoUpdateJTable autoJTable;
	
    /**
     * Creates new form ExpandJPanel
     */
    public ExpandJPanel() {
        initComponents();
        this.setOpaque(false);
        autoJTable = new AutoUpdateJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(378, 300));
        setRequestFocusEnabled(false);

        jTable1.setModel(new MyTableModel());
        jTable1.setTableHeader(null);
        //jTable1.setCellEditor(jTable1.getCellEditor());
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(true);
        jTable1.setFocusable(true);
        jTable1.setMaximumSize(new java.awt.Dimension(370, 30));
        jTable1.setMinimumSize(new java.awt.Dimension(370, 370));
        jTable1.setRowSelectionAllowed(true);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowSorter(null);
        
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    
    // End of variables declaration
    public void updateJTable(Task[] tasks) {
    	autoJTable.updateJTable(tasks);
    }
    
    public static void updateJTable() {
    	autoJTable.updateJTable();
    }
    
    public static void updateJTableWithTasks(Task[] tasks) {
    	autoJTable.updateJTable(tasks);
    }
    
    public static Task[] getAllTasks() {
    	return autoJTable.getTasks();
    }
    
    public static Task[] getSeletedTask() {
    	int[] idx = jTable1.getSelectedRows();
    	Task[] tasks = new Task[idx.length];
    	for(int i=0; i<tasks.length; i++) {
    		tasks[i] = autoJTable.getTasks()[idx[i]];
    	}
    	return tasks;
    }
    
    class MyTableModel extends DefaultTableModel{
    	MyTableModel() {
    		super(
    			new Object [][] {null},
    			new String [] {"Title 1"});
    	}
    	
    	@Override
    	public boolean isCellEditable(int row, int column) {
			return false;
    	}
    }
}
