/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import data.*;
/**
 *
 * @author Ramon
 */
public class ExpandComponent{

    // Variables declaration - do not modify
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JLayeredPane jLayeredPane1;
    private static MyTableModel myTableModel;
    // End of variables declaration
	static AutoUpdateJTable autoJTable;
	
    /**
     * Creates new form ExpandJPanel
     */
    public static void initialize() {
        initComponents();
        autoJTable = new AutoUpdateJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private static void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        myTableModel = new MyTableModel();
     
        jTable1.setModel(myTableModel);
        jTable1.setTableHeader(null);
        jTable1.setCellEditor(jTable1.getCellEditor());
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(true);
        jTable1.setFocusable(true);
        jTable1.setMaximumSize(new java.awt.Dimension(370, 30));
        jTable1.setMinimumSize(new java.awt.Dimension(370, 370));
        jTable1.setRowSelectionAllowed(true);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowSorter(null);
        
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBounds(15, 115, 370, 270);
        
        
    }// </editor-fold>
    
    public static JScrollPane getJScrollPane() {
    	return jScrollPane1;
    }
    
    public static JTable getJTable() {
    	return jTable1;
    }
    
    public static void updateJTable(Task[] tasks) {
    	autoJTable.updateJTable(tasks);
    }
    
    public static void updateJTable() {
    	autoJTable.updateJTable();
    }
    
    public static void updateJTableWithTasks(Task[] tasks) {
    	autoJTable.updateJTable(tasks);
    }
    
    public static Task[] getAllTasks() {
    	return autoJTable.getTasks();
    }
    
    public static Task[] getSeletedTask() {
    	int[] idx = jTable1.getSelectedRows();
    	Task[] tasks = new Task[idx.length];
    	for(int i=0; i<tasks.length; i++) {
    		tasks[i] = autoJTable.getTasks()[idx[i]];
    	}
    	return tasks;
    }
    
    static class MyTableModel extends DefaultTableModel{
    	MyTableModel() {
    		super(
    			new Object [][] {null},
    			new String [] {"Title 1"});
    	}
    	
    	@Override
    	public boolean isCellEditable(int row, int column) {
			return false;
    	}
    }
}
